# Generated by Django 5.1.6 on 2025-02-20 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField()),
                ('post_date', models.DateTimeField(blank=True, verbose_name=datetime.datetime.now)),
                ('post_text', models.TextField()),
                ('photo_main', models.ImageField(upload_to='')),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(upload_to='')),
                ('photo_3', models.ImageField(upload_to='')),
                ('photo_4', models.ImageField(upload_to='')),
                ('photo_5', models.ImageField(upload_to='')),
                ('photo_6', models.ImageField(upload_to='')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bloggers.blogger')),
            ],
        ),
    ]
